# -*- coding: utf-8 -*-
"""matplot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nw_1wyYdCwuh0hOiYE4Cb9PKIDDPo0lp
"""

import matplotlib as mpl
import matplotlib.pyplot as plt

import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0, 10, 100)
plt.plot(x, np.sin(x))
plt.show()

x = np.linspace(0, 10, 100)
plt.plot(x, np.sin(x))
plt.plot(x, np.cos(x))
plt.show()

x = np.linspace(0, 10, 100)
plt.plot(x, np.sin(x))
plt.title("A Sine Curve")
plt.xlabel("x")
plt.ylabel("sin(x)")
plt.show()

x = np.linspace(0, 10, 100)
plt.plot(x, np.sin(x))
plt.xlim(-5, 20)
plt.ylim(-2, 2);
plt.show()

x = np.linspace(0, 10, 100)
plt.plot(x, np.sin(x), color = 'green', linestyle='dashed')
plt.show()

x = np.linspace(0, 10, 100)
plt.plot(x, np.sin(x), color = 'g', linestyle='--')
plt.show()

x = np.linspace(0, 10, 100)
plt.plot(x, np.sin(x), 'g--')
plt.show()

x = np.linspace(0, 10, 100)
plt.plot(x, np.sin(x), 'g--')
plt.plot(x, np.cos(x), 'b-+')
plt.show()

x = np.linspace(0, 10, 100)
plt.plot(x, np.sin(x), 'g--')
plt.plot(x, np.cos(x), 'b-+')
plt.xlim(-1, 12)
plt.ylim(-2, 2);
plt.title("A Sine Curve")
plt.xlabel("x")
plt.ylabel("sin(x)")

plt.show()

rng = np.random.RandomState(0)
x = rng.randn(100)
y = rng.randn(100)
plt.scatter(x, y)
plt.show()

data = np.random.randn(1000)
plt.hist(data)
plt.show()

x = np.linspace(0, 10, 100)
plt.subplot(2, 1, 1)
plt.plot(x, np.sin(x))
plt.subplot(2, 1, 2)
plt.plot(x, np.cos(x));

x = np.linspace(0, 10, 100)
plt.subplot(1, 2, 1)
plt.plot(x, np.sin(x))
plt.subplot(1, 2, 2)
plt.plot(x, np.cos(x));

x = np.linspace(0, 10, 100)
plt.subplot(2, 2, 1)
plt.plot(x, np.sin(x))
plt.subplot(2, 2, 2)
plt.plot(x, np.cos(x));
plt.subplot(2, 2, 3)
rng = np.random.RandomState(0)
x = rng.randn(100)
y = rng.randn(100)
plt.scatter(x, y)
plt.subplot(2, 2, 4)
data = np.random.randn(1000)
plt.hist(data)